title: Trash / Recyclables Images Classifier
description: Classify trash / recyclables images using deep learning
about:


  This is a Trash / Recyclables Images Classifier using Deep Learning built on top of Pytorch & FastAI.


  The project was built originally by [Nidhin Pattaniyil](https://npatta01.github.io)
  
  and [Reshama Shaikh](https://reshamas.github.io) for a food classifier, but has been 
  
  forked and is being used by [Aritro Saha / Axiumin](https://github.com/Axiumin) to create a Trash / Recyclables Image Classifier. 
  
  However, this is not the full version, but a test of how this would work in the real product.



code: https://github.com/SuperMLGCodeSharer/web-deep-learning-classifier

sampleImages:
  - name: cardboard box
    url: https://www.stormtrading.co.uk/ekmps/shops/stgltd/images/large-double-wall-24x18x18-removal-storage-cardboard-boxes-11413-p.jpg
  - name: glass bottle
    url: https://5.imimg.com/data5/MM/UP/MY-40810582/750-ml-wine-bottle-clear-glass-500x500.jpg
  - name: plastic bottle
    url: https://4.imimg.com/data4/EU/YB/MY-6282801/normal-plastic-bottle-500x500.jpg
  - name: eggplant (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/1280px-Solanum_melongena_24_08_2012_%281%29.JPG
  - name: table (not in training)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 
